name: bookdf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  freezed_annotation: ^2.4.1
  chopper: ^7.4.0
  chucker_flutter: ^1.7.2
  dartz: ^0.10.1
  dot_curved_bottom_nav: ^0.0.2
  feather_icons: ^1.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
