name: bookdf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  freezed_annotation: ^2.4.1
  chopper: ^7.4.0
  chucker_flutter: ^1.7.2
  dartz: ^0.10.1
  dot_curved_bottom_nav: ^0.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+3
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  mime: ^1.0.5
  http_parser: ^4.0.2
  shared_preferences: ^2.2.3
  injectable: ^2.4.2
  auto_route: ^8.1.3
  get_it: ^7.7.0
  injectable_generator: ^2.6.1
  iconly: ^1.0.1
  readmore: ^3.0.0
  flutter_pdfview: ^1.3.2
  flutter_cache_manager: ^3.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
